import { ChevronDown } from 'lucide-react';
import React, { useState } from 'react';

const faqs = [
  {
    question: 'What is Findex and how does it work?',
    answer: 'Findex is a synthetic trading platform that simulates real market conditions without any financial risk. Our engine generates price ticks every second, aggregates them into 15-second candlesticks, and allows you to practice trading with virtual tokens.',
  },
  {
    question: 'Is Findex free to use?',
    answer: 'Yes! Findex offers a free tier that includes basic charts, 5 active simulated markets, and community access. We also have Pro and Whale tiers for more advanced features and unlimited markets.',
  },
  {
    question: 'Are the market prices real?',
    answer: 'No, all prices are synthetically generated by our simulation engine. They mimic real-world volatility patterns and market dynamics, but no real money or real order books are involved.',
  },
  {
    question: 'Can I lose real money on Findex?',
    answer: 'Absolutely not! Findex uses only virtual tokens and synthetic markets. There is zero financial risk - you can practice trading strategies, test your skills, and learn market dynamics without ever risking real capital.',
  },
  {
    question: 'How accurate is the simulation?',
    answer: 'Our simulation engine is designed to replicate real market conditions including volatility spikes, trends, and choppy markets. While it\'s not identical to live markets, it provides a realistic training environment for developing trading skills.',
  },
  {
    question: 'Can I use Findex for educational purposes?',
    answer: 'Yes! Findex is perfect for educational institutions, trading academies, and individual learners. Our Whale tier includes admin controls for live classes and the ability to tune volatility settings.',
  },
  {
    question: 'What markets are available?',
    answer: 'We offer a variety of simulated trading pairs including major cryptocurrencies like BTC, ETH, SOL, and more. New markets are added regularly, and Pro/Whale users can access unlimited markets.',
  },
  {
    question: 'How do I get started?',
    answer: 'Simply click "Start Simulating" to create your free account. No credit card required. You\'ll get instant access to our basic features and can upgrade anytime to unlock more advanced capabilities.',
  },
];

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <div className="space-y-3">
      {faqs.map((faq, index) => {
        const isOpen = openIndex === index;
        return (
          <div
            key={index}
            className="bg-surface-dark border border-border-dark rounded-xl overflow-hidden transition-all duration-300 hover:border-primary/50"
          >
            <button
              onClick={() => setOpenIndex(isOpen ? -1 : index)}
              className="w-full p-6 flex items-center justify-between gap-4 hover:bg-surface-muted/30 transition-colors group text-left"
            >
              <h3 className="text-white font-bold text-lg group-hover:text-primary transition-colors flex-1">
                {faq.question}
              </h3>
              <ChevronDown
                className={`w-5 h-5 text-muted-text flex-shrink-0 transition-transform duration-300 ${
                  isOpen ? 'rotate-180' : ''
                }`}
              />
            </button>
            <div
              className={`overflow-hidden transition-all duration-300 ${
                isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
              }`}
            >
              <div className="px-6 pb-6 pt-0">
                <p className="text-muted-text leading-relaxed pt-4 border-t border-border-dark">
                  {faq.answer}
                </p>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default FAQ;

